<a href="https://colab.research.google.com/github/MariaZharova/Skillfactory_projects/blob/main/SF_RecSys_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
clicks = pd.read_csv('/content/drive/MyDrive/SF/clicks.csv')
lst_features = pd.read_csv('/content/drive/MyDrive/SF/lst_features.csv')

In [23]:
clicks.head()

timestamp   user_id   offer_id       event_name
0  2022-07-29 00:00:02.095  82662998  275699899  OpenOfferScreen
1  2022-07-29 00:00:20.794  70430591  263076121         Add2Like
2  2022-07-29 00:00:21.326  93889189  254183210  OpenOfferScreen
3  2022-07-29 00:00:26.945  91525566  268686455  OpenOfferScreen
4  2022-07-29 00:00:27.162  78613959  275660175  OpenOfferScreen

In [ ]:
clicks.event_name.unique()

array(['OpenOfferScreen', 'ShowContacts', 'ClickCallButton', 'MakeCall',
       'EndCall'], dtype=object)

In [ ]:
lst_features.head()

offer_id  floornumber             category  totalarea  roomscount  \
0  238017518          1.0             flatRent       27.0         NaN   
1  246784149          NaN       dailyHouseRent       45.0         NaN   
2  256056349          4.0        dailyFlatRent       52.0         1.0   
3  261757282          5.0             flatSale       63.0         3.0   
4  263036059          2.0  newBuildingFlatSale       40.6         1.0   

  flattype        lat        lng       price  
0   studio  45.021564  38.925492     12990.0  
1      NaN  57.248981  32.941303      4000.0  
2    rooms  55.763224  37.605409      5500.0  
3    rooms  54.995849  73.282558   4920000.0  
4    rooms  59.981960  30.338703  14882000.0

In [ ]:
clicks['event_name'].unique()

array(['OpenOfferScreen', 'ShowContacts', 'ClickCallButton', 'MakeCall',
       'EndCall'], dtype=object)

In [ ]:
# event_encoder = {'OpenOfferScreen': 1, 'ShowContacts': 2, 'ClickCallButton': 3, 'MakeCall': 4, 'EndCall': 5}
# clicks['event_name'] = clicks['event_name'].map(event_encoder)
# clicks.drop('timestamp', axis=1, inplace=True)
# clicks.head()

In [ ]:
# floornumber	totalarea	roomscount	isapartments	flattype
lst_features.info() # OK: lat, lng, price, category

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856691 entries, 0 to 856690
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   offer_id     856691 non-null  int64  
 1   floornumber  634746 non-null  float64
 2   category     856691 non-null  object 
 3   totalarea    806624 non-null  float64
 4   roomscount   558479 non-null  float64
 5   flattype     604151 non-null  object 
 6   lat          856691 non-null  float64
 7   lng          856691 non-null  float64
 8   price        856691 non-null  float64
dtypes: float64(6), int64(1), object(2)
memory usage: 58.8+ MB


In [ ]:
lst_features['floornumber'] = lst_features['floornumber'].fillna(lst_features['floornumber'].median())
lst_features['totalarea'] = lst_features['totalarea'].fillna(lst_features['totalarea'].median())
lst_features['roomscount'] = lst_features['roomscount'].fillna(lst_features['roomscount'].median())
lst_features['category'] = lst_features['category'].fillna('-1')
lst_features['flattype'] = lst_features['flattype'].fillna('-1')
lst_features.head()

offer_id  floornumber             category  totalarea  roomscount  \
0  238017518          1.0             flatRent       27.0         2.0   
1  246784149          5.0       dailyHouseRent       45.0         2.0   
2  256056349          4.0        dailyFlatRent       52.0         1.0   
3  261757282          5.0             flatSale       63.0         3.0   
4  263036059          2.0  newBuildingFlatSale       40.6         1.0   

  flattype        lat        lng       price  
0   studio  45.021564  38.925492     12990.0  
1       -1  57.248981  32.941303      4000.0  
2    rooms  55.763224  37.605409      5500.0  
3    rooms  54.995849  73.282558   4920000.0  
4    rooms  59.981960  30.338703  14882000.0

In [ ]:
# lst_features.drop('isapartments', axis=1, inplace=True)

In [ ]:
lst_features.flattype.unique()

array(['studio', '-1', 'rooms', 'openPlan'], dtype=object)

In [ ]:
lst_features.category.unique()

array(['flatRent', 'dailyHouseRent', 'dailyFlatRent', 'flatSale',
       'newBuildingFlatSale', 'cottageRent', 'freeAppointmentObjectRent',
       'cottageSale', 'houseSale', 'landSale', 'industryRent', 'roomSale',
       'industrySale', 'officeRent', 'officeSale', 'shoppingAreaSale',
       'garageSale', 'freeAppointmentObjectSale', 'townhouseSale',
       'businessSale', 'shoppingAreaRent', 'roomRent', 'houseRent',
       'houseShareSale', 'buildingSale', 'garageRent', 'warehouseSale',
       'warehouseRent', 'dailyRoomRent', 'townhouseRent',
       'commercialLandSale', 'flatShareSale', 'houseShareRent',
       'dailyBedRent', 'buildingRent', 'bedRent', 'commercialLandRent',
       'businessRent'], dtype=object)

In [ ]:
from tqdm import tqdm
tqdm.pandas()
def rent_or_sale(arg):
    if 'Sale' in arg:
        return 'Sale'
    if 'Rent' in arg:
        return 'Rent'
lst_features['category'] = lst_features['category'].progress_apply(rent_or_sale)
lst_features.category.unique()

100%|██████████| 856691/856691 [00:01<00:00, 498234.86it/s]


array(['Rent', 'Sale'], dtype=object)

In [ ]:
lst_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 856691 entries, 0 to 856690
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   offer_id     856691 non-null  int64  
 1   floornumber  856691 non-null  float64
 2   category     856691 non-null  object 
 3   totalarea    856691 non-null  float64
 4   roomscount   856691 non-null  float64
 5   flattype     856691 non-null  object 
 6   lat          856691 non-null  float64
 7   lng          856691 non-null  float64
 8   price        856691 non-null  float64
dtypes: float64(6), int64(1), object(2)
memory usage: 58.8+ MB


In [ ]:
import sklearn
sklearn.__version__

'1.2.2'

In [ ]:
# кодируем катфичи
from sklearn.preprocessing import OneHotEncoder
cat_data = lst_features[['category', 'flattype']]
enc = OneHotEncoder()
cat_enc = enc.fit_transform(cat_data).toarray()
display(cat_enc)
print(cat_enc.shape)

array([[1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.]])

(856691, 6)


In [ ]:
# from math import sin, cos
# # def prepare_coordinates(*lat):
# #     x = cos(lat[0]) * cos(lng[1])
# #     y = cos(lat[0]) * sin(lng[1])
# #     z = sin(lat[0]) 
# #     return x, y, z
# #lst_features['x'], lst_features['y'], lst_features['z'] = lst_features[['lat', 'lng']].apply(prepare_coordinates)
# lst_features['cos_lat'] = lst_features['lat'].apply(cos)
# lst_features['cos_lng'] = lst_features['lng'].apply(cos)
# lst_features['sin_lat'] = lst_features['lat'].apply(sin)
# lst_features['sin_lng'] = lst_features['lng'].apply(sin)
# lst_features['x'] = lst_features['cos_lat'] * lst_features['cos_lng']
# lst_features['y'] = lst_features['cos_lat'] * lst_features['sin_lng']
# lst_features['z'] = lst_features['sin_lat']
# lst_features.drop(['cos_lat', 'cos_lng', 'sin_lat', 'sin_lng', 'lat', 'lng'], inplace=True, axis=1)
# lst_features.head()

In [ ]:
lst_features.head()

offer_id  floornumber category  totalarea  roomscount flattype        lat  \
0  238017518          1.0     Rent       27.0         2.0   studio  45.021564   
1  246784149          5.0     Rent       45.0         2.0       -1  57.248981   
2  256056349          4.0     Rent       52.0         1.0    rooms  55.763224   
3  261757282          5.0     Sale       63.0         3.0    rooms  54.995849   
4  263036059          2.0     Sale       40.6         1.0    rooms  59.981960   

         lng       price  
0  38.925492     12990.0  
1  32.941303      4000.0  
2  37.605409      5500.0  
3  73.282558   4920000.0  
4  30.338703  14882000.0

In [ ]:
# масштабирование числовых признаков
from sklearn.preprocessing import MinMaxScaler
num_cols = lst_features.drop(['offer_id', 'category', 'flattype'], axis=1)
scaler = MinMaxScaler()
num_cols = scaler.fit_transform(num_cols)
#print(np.max(num_cols), np.min(num_cols))

In [ ]:
import numpy as np
ID = np.array(lst_features['offer_id'])
lst_features_final = np.hstack((ID.reshape((len(ID), 1)), num_cols, cat_enc))
print(lst_features_final.shape)
lst_features_final

(856691, 13)


array([[2.38017518e+08, 3.17460317e-02, 1.73333449e-05, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.46784149e+08, 6.34920635e-02, 2.93333529e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.56056349e+08, 5.55555556e-02, 3.40000227e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [2.75521097e+08, 8.73015873e-02, 1.96000131e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75672461e+08, 8.73015873e-02, 4.14666943e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75950340e+08, 3.96825397e-02, 2.73333516e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [ ]:
lst_features_Jaccar = np.hstack((ID.reshape((len(ID), 1)), cat_enc)).astype(int)

In [ ]:
def Jaccar_index(vec1, vec2):
    return (np.sum(vec1 & vec2)) / (np.sum(vec1 | vec2))

def Jaccar_index1(vec1, vec2):
    g = np.sum(np.bitwise_and(vec1, vec2))
    return g / (np.sum(vec1) + np.sum(vec2) - g)

In [ ]:
a = lst_features_Jaccar[0][1:]
b = lst_features_Jaccar[1][1:]

In [ ]:
lst_features.iloc[0]

offer_id       238017518
floornumber          1.0
category            Rent
totalarea           27.0
roomscount           2.0
flattype          studio
lat            45.021564
lng            38.925492
price            12990.0
Name: 0, dtype: object

In [ ]:
lst_features.iloc[51]

offer_id       275908181
floornumber          4.0
category            Rent
totalarea           30.0
roomscount           2.0
flattype          studio
lat            55.554629
lng            37.465173
price            38000.0
Name: 51, dtype: object

In [ ]:
best_Jaccar_index = 0 # рабочая переменная для нахождения лучшего значения индекса Жаккара
best_rows = [] # список для хранения наиболее похожих объявлений
for i in range(1, lst_features_Jaccar.shape[0]):
    Jaccar_i = Jaccar_index(lst_features_Jaccar[0][1:], lst_features_Jaccar[i][1:])
    if best_Jaccar_index <= Jaccar_i:
        best_Jaccar_index = Jaccar_i
        best_rows.append(i)
len(best_rows)

17320

In [ ]:
np.bitwise_and(a, b)

array([1, 0, 0, 0, 0, 0])

In [ ]:
Jaccar_index1(a, b)

0.3333333333333333

In [ ]:
clicks[(clicks['user_id'] == '50044273') & (clicks['event_name'] == 'Add2Like')]

Empty DataFrame
Columns: [timestamp, user_id, offer_id, event_name]
Index: []

In [ ]:
lst_features_final_df = pd.DataFrame(data=lst_features_final,
          index=np.array(range(lst_features_final.shape[0])),
          columns=np.array(range(lst_features_final.shape[1])))
lst_features_final_df.head()

0         1         2         3         4         5   \
0  238017518.0  0.031746  0.000017  0.043478  0.122610  0.119515   
1  246784149.0  0.063492  0.000029  0.043478  0.557294  0.081969   
2  256056349.0  0.055556  0.000034  0.021739  0.504475  0.111233   
3  261757282.0  0.063492  0.000041  0.065217  0.477195  0.335078   
4  263036059.0  0.039683  0.000026  0.021739  0.654451  0.065640   

             6    7    8    9    10   11   12  
0  1.298900e-06  1.0  0.0  0.0  0.0  0.0  1.0  
1  3.999000e-07  1.0  0.0  1.0  0.0  0.0  0.0  
2  5.499000e-07  1.0  0.0  0.0  0.0  1.0  0.0  
3  4.919999e-04  0.0  1.0  0.0  0.0  1.0  0.0  
4  1.488200e-03  0.0  1.0  0.0  0.0  1.0  0.0

In [ ]:
lst_features_final_np = lst_features_final_df.to_numpy()

In [ ]:
lst_features_final_np

array([[2.38017518e+08, 3.17460317e-02, 1.73333449e-05, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.46784149e+08, 6.34920635e-02, 2.93333529e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.56056349e+08, 5.55555556e-02, 3.40000227e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [2.75521097e+08, 8.73015873e-02, 1.96000131e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75672461e+08, 8.73015873e-02, 4.14666943e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75950340e+08, 3.96825397e-02, 2.73333516e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [ ]:
clicks50044273 = clicks[clicks['user_id'] == '50044273']['offer_id'].unique()
offer276480422 = lst_features_final_df[lst_features_final_df[0] == 276480422].to_numpy()
#offer276480422
lst_features_for50044273 = lst_features_final_df[~lst_features_final_df[0].isin(clicks50044273)].to_numpy()

In [ ]:
lst_features_for50044273

array([[2.38017518e+08, 3.17460317e-02, 1.73333449e-05, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.46784149e+08, 6.34920635e-02, 2.93333529e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.56056349e+08, 5.55555556e-02, 3.40000227e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [2.75521097e+08, 8.73015873e-02, 1.96000131e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75672461e+08, 8.73015873e-02, 4.14666943e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75950340e+08, 3.96825397e-02, 2.73333516e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [ ]:
def cos_distance(vec1, vec2):
    return np.sum(vec1 * vec2) / np.sqrt(np.sum(np.square(vec1))) * np.sqrt(np.sum(np.square(vec2)))

In [ ]:
lst_features_for50044273

array([[2.38017518e+08, 3.17460317e-02, 1.73333449e-05, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.46784149e+08, 6.34920635e-02, 2.93333529e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.56056349e+08, 5.55555556e-02, 3.40000227e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [2.75521097e+08, 8.73015873e-02, 1.96000131e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75672461e+08, 8.73015873e-02, 4.14666943e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.75950340e+08, 3.96825397e-02, 2.73333516e-05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00]])

In [ ]:
cos_distance(lst_features_for50044273[0], lst_features_for50044273[100])

7.0566864901620024e+16

In [ ]:
score_list = dict()
for vec in lst_features_for50044273:
    score_list[vec[0]] = cos_distance(offer276480422, vec)

In [ ]:
ans =dict(sorted(score_list.items(), key=lambda item: item[1]))
dict(list(ans.items())[-5:])

{276605251.0: 7.651046488077301e+16,
 276605608.0: 7.651066237704966e+16,
 276605671.0: 7.651069722936024e+16,
 276605734.0: 7.651073208167875e+16,
 276605862.0: 7.651080289276304e+16}

# collaborative filtering1

In [4]:
! pip install category_encoders

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 KB 3.6 MB/s eta 0:00:00


In [3]:
import category_encoders as ce
# ord_encoder_user = ce.OrdinalEncoder()
# ord_encoder_offer = ce.OrdinalEncoder()
# clicks['user_id_enc'] = ord_encoder_user.fit_transform(clicks['user_id'])['user_id'] - 1
# clicks['offer_id_enc'] = ord_encoder_offer.fit_transform(clicks['offer_id'].apply(str))['offer_id'] - 1
# clicks.head()

In [6]:
clicks['event_name'].unique()

array(['OpenOfferScreen', 'Add2Like', 'ClickCallButton', 'MakeCall',
       'EndCall'], dtype=object)

In [7]:
event_encoder = {'OpenOfferScreen': 1, 'Add2Like': 2, 'ClickCallButton': 3, 'MakeCall': 4, 'EndCall': 5}
clicks['event_name_enc'] = clicks['event_name'].map(event_encoder)
clicks.head()

timestamp   user_id   offer_id       event_name  user_id_enc  \
0  2022-07-29 00:00:02.095  82662998  275699899  OpenOfferScreen            0   
1  2022-07-29 00:00:20.794  70430591  263076121         Add2Like            1   
2  2022-07-29 00:00:21.326  93889189  254183210  OpenOfferScreen            2   
3  2022-07-29 00:00:26.945  91525566  268686455  OpenOfferScreen            3   
4  2022-07-29 00:00:27.162  78613959  275660175  OpenOfferScreen            4   

   offer_id_enc  event_name_enc  
0             0               1  
1             1               2  
2             2               1  
3             3               1  
4             4               1

In [6]:
from scipy.sparse import csr_matrix
# csr_user_item = csr_matrix((clicks['event_name_enc'], (clicks['user_id_enc'], clicks['offer_id_enc'])))

In [115]:
csr_user_item.shape

(34998, 858396)

In [30]:
# a = csr_user_item.toarray()

In [45]:
np.sum(csr_user_item[23024, :].toarray())

2622

In [10]:
target_row = csr_user_item[:, 23024].toarray().reshape(-1)

In [20]:
from tqdm import tqdm
import numpy as np
b = []
target_row = csr_user_item[:, 23024].toarray().reshape(-1)
for i in tqdm(range(100, csr_user_item.shape[1] // 2, 3)):
   if i == 23024:
       continue
   tmp = csr_user_item[:, i].toarray().reshape(-1)
   b.append(np.sum(target_row & tmp))
print(np.argmax(b))

100%|██████████| 143033/143033 [17:12<00:00, 138.50it/s]

7218


In [22]:
print(np.argmax(b))
#b

7218


In [11]:
csr_user_item[:10, :10].toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 2]])

In [72]:
vec1 = csr_user_item[23024, :].toarray()[0]
vec2 = csr_user_item[15604, :].toarray()[0]
new_vec1 = np.array([])
new_vec2 = np.array([])
for i in range(len(vec1)):
    if vec1[i] != 0 and vec2[i] != 0:
        new_vec1 = np.append(new_vec1, vec1[i])
        new_vec2 = np.append(new_vec2, vec2[i])

In [77]:
new_vec2 * 4

array([  4.,   8.,   4.,  52.,   4., 400.,  68.,   4.,  56.,   4.,   4.,
         4.,   4.,   4., 240.,  68., 164.,   4.,   4.,   4.])

In [116]:
def corr_Pirs(a, b):
    dif_a = a - np.mean(a)
    dif_b = b - np.mean(b)
    return np.sum(dif_a * dif_b) / (np.sqrt(np.sum(dif_a**2)) * np.sqrt(np.sum(dif_b**2)))
corr_Pirs(new_vec1, new_vec2)

/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.9/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
<ipython-input-116-d7434816d65c>:4: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum(dif_a * dif_b) / (np.sqrt(np.sum(dif_a**2)) * np.sqrt(np.sum(dif_b**2)))


nan

In [97]:
# задание 3.5
vec1 = csr_user_item[19, :].toarray()[0]
vec2 = csr_user_item[17234, :].toarray()[0]
new_vec1 = np.array([])
new_vec2 = np.array([])
for i in range(len(vec1)):
    if vec1[i] != 0 and vec2[i] != 0:
        new_vec1 = np.append(new_vec1, vec1[i])
        new_vec2 = np.append(new_vec2, vec2[i])
corr_Pirs(new_vec1, new_vec2)

/usr/local/lib/python3.9/dist-packages/numpy/core/fromnumeric.py:3474: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.9/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
<ipython-input-79-d7434816d65c>:4: RuntimeWarning: invalid value encountered in double_scalars
  return np.sum(dif_a * dif_b) / (np.sqrt(np.sum(dif_a**2)) * np.sqrt(np.sum(dif_b**2)))


nan

In [94]:
b = []
target_row = csr_user_item[19,:].toarray()
for i in tqdm(range(csr_user_item.shape[0])):
   if i == 19:
       continue
   tmp = csr_user_item[i, :].toarray()
   b.append(np.sum(target_row & tmp))
print(np.argmax(b))

100%|██████████| 34998/34998 [01:25<00:00, 411.33it/s]

17234


In [95]:
print(np.argmax(b))

17234


item-based

In [25]:
mean_user_ratings = np.array([])
for i in tqdm(range(csr_user_item.shape[0])):
    tmp_vec = csr_user_item[i, :].toarray()[0]
    tmp_vec = np.where(tmp_vec != 0, tmp_vec, np.nan) # удалим нули, они не должны участвовать при расчёте среднего
    mean_user_ratings = np.append(mean_user_ratings, np.nanmean(tmp_vec))
mean_user_ratings

100%|██████████| 34998/34998 [03:58<00:00, 146.78it/s]


array([1.12121212, 3.01935484, 1.        , ..., 1.75373134, 1.23076923,
       3.06930693])

In [26]:
mean_user_ratings1 = mean_user_ratings

In [30]:
len(mean_user_ratings)

34998

In [31]:
vec1 = csr_user_item[:, 23024].toarray().reshape(-1)
vec2 = csr_user_item[:, 7218].toarray().reshape(-1)
new_vec1 = np.array([])
new_vec2 = np.array([])
for i in range(len(vec1)):
    if vec1[i] != 0 and vec2[i] != 0:
        new_vec1 = np.append(new_vec1, vec1[i])
        new_vec2 = np.append(new_vec2, vec2[i])
    else:
        np.delete(mean_user_ratings, i)

In [33]:
def corr_Pirs_items(a, b, mean_user_ratings):
    dif_a = a - mean_user_ratings
    dif_b = b - mean_user_ratings
    return np.sum(dif_a * dif_b) / (np.sqrt(np.sum(dif_a**2)) * np.sqrt(np.sum(dif_b**2)))
corr_Pirs(vec1, vec2, mean_user_ratings)

0.9975035275435579

# collaborative filtering 2

In [3]:
import category_encoders as ce
ord_encoder_user = ce.OrdinalEncoder()
ord_encoder_offer = ce.OrdinalEncoder()
clicks['user_id_enc'] = ord_encoder_user.fit_transform(clicks['user_id'])['user_id'] - 1
clicks['offer_id_enc'] = ord_encoder_offer.fit_transform(clicks['offer_id'].apply(str))['offer_id'] - 1

event_encoder = {'OpenOfferScreen': 1, 'Add2Like': 2, 'ClickCallButton': 3, 'MakeCall': 4, 'EndCall': 5}
clicks['event_name_enc'] = clicks['event_name'].map(event_encoder)
clicks.head()


timestamp   user_id   offer_id       event_name  user_id_enc  \
0  2022-07-29 00:00:02.095  82662998  275699899  OpenOfferScreen            0   
1  2022-07-29 00:00:20.794  70430591  263076121         Add2Like            1   
2  2022-07-29 00:00:21.326  93889189  254183210  OpenOfferScreen            2   
3  2022-07-29 00:00:26.945  91525566  268686455  OpenOfferScreen            3   
4  2022-07-29 00:00:27.162  78613959  275660175  OpenOfferScreen            4   

   offer_id_enc  event_name_enc  
0             0               1  
1             1               2  
2             2               1  
3             3               1  
4             4               1

In [4]:
from scipy.sparse import csr_matrix
clicks_train = clicks.iloc[:clicks.shape[0]//3, :]
clicks_test = clicks.iloc[clicks.shape[0]//3:, :]
csr_user_item_train = csr_matrix((clicks_train['event_name_enc'], (clicks_train['user_id_enc'], clicks_train['offer_id_enc'])))

In [5]:
csr_user_item_train.shape

(34998, 514563)

In [6]:
# составим тестовый датасет
train_users = set(clicks_train['user_id_enc'].values)
train_items = set(clicks_train['offer_id_enc'].values)

clicks_test = clicks_test[(clicks_test['user_id_enc'].isin(train_users)) & 
                      (clicks_test['offer_id_enc'].isin(train_items))]

# составим словарь
test_dict = {}
for user_id in clicks_test['user_id_enc'].drop_duplicates().values:
    test_dict[user_id] = list(clicks_test[clicks_test['user_id_enc'] == user_id]['offer_id_enc'])


In [ ]:
import scipy.sparse as sp
from scipy.sparse.linalg import svds
from scipy.linalg import sqrtm
import numpy as np

def svd(data, k):  
    U, s, V = svds(data.asfptype(), k=k) 
    s = np.diag(s)
    s_root = sqrtm(s)
    Usk = np.dot(U, s_root) 
    skV = np.dot(s_root, V) 
    UsV = np.dot(Usk, skV)
    print("SVD-разложение готово") 
    return UsV
pred_svd = svd(csr_user_item_train, 2)

In [ ]:
pred_svd.shape

In [ ]:
test_dict = {}
for user_id in data_test['uid_device_enc'].drop_duplicates().values:
    test_dict[user_id] = list(data_test[data_test['uid_device_enc'] == user_id]['id_enc'])
test_dict

In [ ]:
# prepare predicted data for evaluation
#diff = pred_svd - csr_user_item_train

#pred_dict = {}
#for i in test_dict.keys():
#    print('f')
#    test_dict[i] = sorted(diff[user_id], reverse=True)

pred_list = []
for i in range(pred_svd.shape[0]):
  pred_list.append(np.argsort(diff[i])[::-1])
pred_list[:5]

In [ ]:
from sklearn.utils import column_or_1d
from sklearn.utils.multiclass import type_of_target

def precision_at_k(y_true, y_score, k):
    """
        INPUT:
        y_true - list of true test values for one user
        y_score - list of predictions values foro one user
        k - level of precision
        OUTPUT:
        ans - precision at k :)
    """
    ans = 0
    counter = 0
    for row in y_true:
        counter += 1
        if counter > k:
            return ans
        if row in y_score:
            ans += 1 / k
    return ans

In [ ]:
prec_fin = 0
for ind, val in test_dict.items():
    prec_fin += precision_at_k(val, pred_list[ind], 5)
prec_fin /= len(test_dict)